from typing import List, TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph

    Attributes:
    question: this is important to understand whether the document retrieved is relevant to the question
    generation: answer generated by the LLM
    web_search: flag to understand whether we need to retrieve info from the web
    documents: docs retrieved from the RAG or from the web search
    """

    question: str
    generation: str
    web_search: bool
    documents: List[str]
